### ISSUE TITLE
having error compiling  rom

### ISSUE THREAD

**Issue by k2wl** [cristianomatos/android_frameworks_base#10]
hi
i know i am repeating the issue.
can you give me proper roomservice.xml
i cant see it in previous issue.
the error is 
i want to compile this rom for my device i9082.
please help
"
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-xxhdpi
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-hdpi
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-xhdpi
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-mdpi "

sorry for the trouble.

my email is kar2wlan@gmail.com

thank you

**Comment by alviteri** [comment]
Use cristiano's android_frameworks_opt_cards seems you are using that from slim and it contains holodark resources for trds crdroid doesn't has trds
