### ISSUE TITLE
invalid resource directory

### ISSUE THREAD

**Issue by moonlightly** [cristianomatos/android_frameworks_base#5]
HI,I used your source and cm11's and then build crdroid,and tells below errors.
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-xxhdpi
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-hdpi
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-xhdpi
invalid resource directory name: frameworks/opt/cards/res/drawable-holodark-mdpi

can you fix them or your can upload your manifest for us.i'm very love your crdroid but not contain full chinese.

**Comment by cristianomatos** [comment]
For sure you're not up to date with my repos.
I removed trds and you still looking for dependencies.

**Comment by moonlightly** [comment]
If not have frameworks_opt_cards,build will calls that repository

<remove-project name="CyanogenMod/android_vendor_cm" />
  <project name="cristianomatos/android_vendor_cm" path="vendor/cm" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_DSPManager" />
  <project name="cristianomatos/android_packages_apps_DSPManager" path="packages/apps/DSPManager" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Dialer" />
  <project name="cristianomatos/android_packages_apps_Dialer" path="packages/apps/Dialer" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_InCallUI" />
  <project name="cristianomatos/android_packages_apps_InCallUI" path="packages/apps/InCallUI" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_services_Telephony" />
  <project name="cristianomatos/android_packages_services_Telephony" path="packages/services/Telephony" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Mms" />
  <project name="cristianomatos/android_packages_apps_Mms" path="packages/apps/Mms" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_MediaProvider" />
  <project name="cristianomatos/android_packages_providers_MediaProvider" path="packages/providers/MediaProvider" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_DownloadProvider" />
  <project name="cristianomatos/android_packages_providers_DownloadProvider" path="packages/providers/DownloadProvider" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_system_media" />
  <project name="cristianomatos/android_system_media" path="system/media" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_frameworks_base" />
  <project name="cristianomatos/android_frameworks_base" path="frameworks/base" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Settings" />
  <project name="cristianomatos/android_packages_apps_Settings" path="packages/apps/Settings" remote="github" revision="cm-11.0" />
  <project name="cristianomatos/android_packages_apps_ScreenRecorder" path="packages/apps/ScreenRecorder" remote="github" revision="cm-11.0" />
  <project name="cristianomatos/frameworks_opt_cards" path="frameworks/opt/cards" remote="github" revision="slim-recent" />
  <remove-project name="CyanogenMod/android_packages_apps_CMUpdater" />

**Comment by cristianomatos** [comment]
Use this in your roomservice.xml

<remove-project name="CyanogenMod/android_vendor_cm" />
  <project name="cristianomatos/android_vendor_cm" path="vendor/cm" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_DSPManager" />
  <project name="cristianomatos/android_packages_apps_DSPManager" path="packages/apps/DSPManager" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Dialer" />
  <project name="cristianomatos/android_packages_apps_Dialer" path="packages/apps/Dialer" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_InCallUI" />
  <project name="cristianomatos/android_packages_apps_InCallUI" path="packages/apps/InCallUI" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_services_Telephony" />
  <project name="cristianomatos/android_packages_services_Telephony" path="packages/services/Telephony" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Mms" />
  <project name="cristianomatos/android_packages_apps_Mms" path="packages/apps/Mms" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_MediaProvider" />
  <project name="cristianomatos/android_packages_providers_MediaProvider" path="packages/providers/MediaProvider" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_DownloadProvider" />
  <project name="cristianomatos/android_packages_providers_DownloadProvider" path="packages/providers/DownloadProvider" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_system_media" />
  <project name="cristianomatos/android_system_media" path="system/media" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_frameworks_base" />
  <project name="cristianomatos/android_frameworks_base" path="frameworks/base" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Settings" />
  <project name="cristianomatos/android_packages_apps_Settings" path="packages/apps/Settings" remote="github" revision="cm-11.0" />
  <project name="cristianomatos/android_packages_apps_ScreenRecorder" path="packages/apps/ScreenRecorder" remote="github" revision="cm-11.0" />
  <project name="cristianomatos/frameworks_opt_cards" path="frameworks/opt/cards" remote="github" revision="slim-recent" />
  <remove-project name="CyanogenMod/android_packages_apps_CMUpdater" />

**Comment by moonlightly** [comment]
This is my roomservice.xml

<remove-project name="CyanogenMod/android_packages_apps_Settings" path="packages/apps/Settings" />
  <project name="cristianomatos/android_packages_apps_Settings" path="packages/apps/Settings" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_frameworks_base" path="frameworks/base" />
  <project name="cristianomatos/android_frameworks_base" path="frameworks/base" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_vendor_cm" path="vendor/cm" />
  <project name="cristianomatos/android_vendor_cm" path="vendor/cm" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_services_Telephony" path="packages/services/Telephony" />
  <project name="cristianomatos/android_packages_services_Telephony" path="packages/services/Telephony" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_MediaProvider" path="packages/providers/MediaProvider" />
  <project name="cristianomatos/android_packages_providers_MediaProvider" path="packages/providers/MediaProvider" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_InCallUI" path="packages/apps/InCallUI" />
  <project name="cristianomatos/android_packages_apps_InCallUI" path="packages/apps/InCallUI" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_DSPManager" path="packages/apps/DSPManager" />
  <project name="cristianomatos/android_packages_apps_DSPManager" path="packages/apps/DSPManager" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Dialer" path="packages/apps/Dialer" />
  <project name="cristianomatos/android_packages_apps_Dialer" path="packages/apps/Dialer" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_apps_Mms" path="packages/apps/Mms" />
  <project name="cristianomatos/android_packages_apps_Mms" path="packages/apps/Mms" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_DownloadProvider" path="packages/providers/DownloadProvider" />
  <project name="cristianomatos/android_packages_providers_DownloadProvider" path="packages/providers/DownloadProvider" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_system_media" path="system/media" />
  <project name="cristianomatos/android_system_media" path="system/media" remote="github" revision="cm-11.0" />
  <remove-project name="CyanogenMod/android_packages_providers_ThemesProvider" path="packages/providers/ThemesProvider" />
  <project name="cristianomatos/android_packages_providers_ThemesProvider" path="packages/providers/ThemesProvider" remote="github" revision="cm-11.0" />
  <project name="cristianomatos/frameworks_opt_cards" path="frameworks/opt/cards" remote="github" revision="kk4.4" />
  <project name="cristianomatos/android_packages_apps_PerformanceControl" path="packages/apps/PerformanceControl" remote="github" revision="crDroid-kk" />
  <project name="cristianomatos/android_packages_apps_KernelTweaker" path="packages/apps/KernelTweaker" remote="github" revision="crDroid-kk" />
  <project name="cristianomatos/android_packages_apps_ScreenRecorder" path="packages/apps/ScreenRecorder" remote="github" revision="cm-11.0" />
  <remove-project path="device/sample" name="CyanogenMod/android_device_sample" />
  <project name="cristianomatos/android_device_sample" path="device/sample" remote="github" revision="cm-11.0" />
  <remove-project path="packages/apps/ThemeChooser" name="CyanogenMod/android_packages_apps_ThemeChooser" />
  <project name="cristianomatos/android_packages_apps_ThemeChooser" path="packages/apps/ThemeChooser" remote="github" revision="cm-11.0" />

**Comment by moonlightly** [comment]
I Can't see the above content,is white. Can you push your roomservice.xml to local_manifests? very thanks

**Comment by cristianomatos** [comment]
Please, close this issue.

Already send you my roomservice.xml through email

Thanks

**Comment by k2wl** [comment]
i am having this same error. can you please give me that roomserive.xml
sorry for trouble.
