### ISSUE TITLE
frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:4199: Can not find symbol

### ISSUE THREAD

**Issue by moonlightly** [cristianomatos/android_frameworks_base#7]
frameworks/base/policy/src/com/android/internal/policy/impl/PhoneWindowManager.java:4199: Can not find symbol
 mGlobalMenu
  com.android.internal.policy.impl.PhoneWindowManager
        mHandler.post(mGlobalMenu);
                      ^

**Comment by cristianomatos** [comment]
It's fixed. Just try to build or cherry pick again

**Comment by alviteri** [comment]
https://github.com/SlimRoms/frameworks_base/commit/c6add8f9b0d1f608c51196c1f578839b1a3aa720

method

private final Runnable mGlobalMenu = new Runnable() {
-        @Override
-        public void run() {
-            sendCloseSystemWindows(SYSTEM_DIALOG_REASON_GLOBAL_ACTIONS);
-            showGlobalActionsDialog(false);
-        }
-    };

I solve with this

**Comment by cristianomatos** [comment]
That's not a real issue. My branch more updated for now is slimpie and the rest needed for this was one step further in [WIP] SlimPIE commit. Yesterday i fix this including the codes in such commit.
Just build again using cm-11.0 branch or build with SlimPIE using slimpie branch in settings and base

**Comment by alviteri** [comment]
ok but with your commit I have an error everytime when I want build my rom and I can solve that error only with this override without him I have an error in build everytime , anyway thanks for the reply

**Comment by cristianomatos** [comment]
It still one commit ahead! Just check slimpie branch.
But i will put this in power menu fix commit
